### ISSUE TITLE
Cancel Button does not dismiss QBImagePickerController iOS 8

### ISSUE THREAD

**Issue by chemjournal** [questbeat/QBImagePickerController#44]
In iOS 8, Pressing the Cancel button does not dismiss the Controller. How can we fix this?

**Comment by tygonorg** [comment]
you can implement method
-(void) qb_imagePickerControllerDidCancel:(QBImagePickerController *)imagePickerController{
    [imagePickerController dismissViewControllerAnimated:YES completion:nil];
}
it will close when cancel click
